### ISSUE TITLE
Bento skeleton not behaving - Glaidys Normal Cock $v2.0-alpha.1 - 051718

### ISSUE THREAD

**Issue by TinySKNK** [SL-SKNK/Glaidys#13] opened 2018-05-17 20:00 UTC
Submitter: Incognitustealthy Resident
Upon attachment and 'Grab' of the bento skeleton, the weenie turns into a horrifying ball of distended meat. See included images.
https://i.imgur.com/1aQv122.png - Front
https://i.imgur.com/cQxvzZg.png - Side
https://i.imgur.com/eH4F8E0.png - Back

**Comment by Tokeli** [comment] 2018-05-18 14:31
Duplicate of #8

**Closed by Tokeli** 2018-05-18 14:31 UTC
