### ISSUE TITLE
SKNK Glaidys - Normal Cock $v2.0-alpha.1

### ISSUE THREAD

**Issue by TinySKNK** [SL-SKNK/Glaidys#15] opened 2018-05-18 06:30 UTC
Submitter: damienAlexeyev Resident
The cock attached inside my body, appears scrunched down, the offset controls don't work, I cannot reposition it by any means. I also get a round white prim/mesh object thing that attaches to myself, I can reposition that thing via edit tools but the cock doesnt budge no matter what I do, HUD doesnt work, edit doesn't either. I use the last version of the Kuroo body and the Glaidys is the cock I've been using since forever with no issues, even when I attach a bento tail to myself.
Feel free to contact me inworld if you need, my main account is Ranshiinsitha Parabola (I use your cock in my alt but I log in more often on my main), I log in around 8pm SLT most of the time when Im not too tired from school.

**Comment by Tokeli** [comment] 2018-05-18 14:31
Duplicate of #8

**Closed by Tokeli** 2018-05-18 14:31 UTC
