### ISSUE TITLE
It doesn't work at all. Is it rigged up at all?

### ISSUE THREAD

**Issue by TinySKNK** [SL-SKNK/Glaidys#11] opened 2018-05-17 14:34 UTC
Submitter: Emmie Morpork
I put the penis on and it just looks like a garbled mess up inside my crotch, I don't think it's rigged at all. There's also a white sphere prim in there (which contains a bunch of scripts and animation files) that is editable and I can move it around but why is this here if the penis is bento fitted mesh object? The penis never comes out and hangs down, it won't change states. Running an animation does nothing, it just remains all crammed up inside my body.. is this even rigged up? it just remains a "wad" up inside my crotch regardless what I do with the HUD.  I trued to reset the scripts but it still behaves the same, in that it does nothing and remains a wad of polygons inside my body.

**Comment by Tokeli** [comment] 2018-05-17 16:42
Duplicate of #8

**Closed by Tokeli** 2018-05-17 16:42 UTC
